{% set name = "rocksdict" %}
{% set version = "0.3.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rocksdict/RocksDict/archive/v{{ version }}.tar.gz
  sha256: 2f5371e2b7e9aeb2b36e85ff4281607eae1eb76e5627f3b78577e1be9629520f
  patches:
    # https://github.com/rocksdict/RocksDict/compare/v0.3.24...v0.3.24-musllinux-patch
    - 001-fix-rust-dep.patch

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - LIBCLANG_PATH=$BUILD_PREFIX/lib  # [not win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - clangdev
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

test:
  imports:
    - rocksdict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rocksdict/RocksDict
  doc_url: https://rocksdict.github.io/RocksDict/rocksdict.html
  summary: Python fast on-disk dictionary; RocksDB & SpeeDB Python binding
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
