{% set name = "rocksdict" %}
{% set version = "0.3.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Congyuwang/RocksDict/archive/v{{ version }}.tar.gz
  sha256: 2f5371e2b7e9aeb2b36e85ff4281607eae1eb76e5627f3b78577e1be9629520f

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - LIBCLANG_PATH=$BUILD_PREFIX/lib  # [not win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - clangdev
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

test:
  imports:
    - rocksdict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Congyuwang/RocksDict
  doc_url: https://congyuwang.github.io/RocksDict/rocksdict.html
  summary: Python fast on-disk dictionary; RocksDB & SpeeDB Python binding
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
